# Standard configuration

auto: true
permalink: /:year/:month/:title
pygments: true
exclude: ['README.md','CNAME']
markdown: rdiscount
rdiscount extensions: [smart]
lsi: true

# Configuration required for some pages

domain: ant.onio.org
title: El blog de Antonio
author: Antonio Villamarin
# email: me@example.com

# configuration for ehancements,

analytics_account: UA-3709753-8

github_account: zeura

facebook_account: villamarin

linkedin_account: villamarin

twitter_account: antvillamarin

plus_account: 114899077462139891523



# disqus:
# id: disqusid

