# Standard configuration

auto: true
permalink: /:year/:month/:title.html
pygments: true
exclude: ['README.md','CNAME']
markdown: rdiscount
rdiscount:
  extensions: [smart]

source:      .
destination: ./_site

url: ant.onio.org
title: El blog de Antonio
author: Antonio Villamarin
# email: me@example.com

analytics:
  account: UA-3709753-8

social:
  github: zeura
  facebook: villamarin
  linkedin: villamarin
  twitter: antvillamarin
  plus: 114899077462139891523
