# Standard configuration

auto: true
permalink: /:year/:month/:title.html
pygments: true

exclude: ['README.md','.gitignore']
markdown: rdiscount
rdiscount:
  extensions: [smart]

paginate: 5
lsi: true

url: ant.onio.org
title: El blog de Antonio
author: Antonio Villamarin
