# Standard configuration

auto: true
permalink: /:year/:month/:title.html
pygments: true
#paginate: 5
lsi: true
exclude: ['README.md','CNAME','.gitignore','archivo.html']
markdown: rdiscount
rdiscount:
  extensions: [smart]

url: ant.onio.org
title: El blog de Antonio
author: Antonio Villamarin
