auto: true
permalink: date
pygments: true
exclude: ['README.md','.gitignore','CNAME','blog.sublime-project','blog.sublime-workspace']
markdown: rdiscount
rdiscount:
    extensions: [smart]
paginate: 5
lsi: true
url: 'anvius.github.io'
title: Mi blog sobre tecnología
author: Antonio Villamarin
